# Generated by Django 4.2 on 2023-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_contactinfo_rename_blogdata_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
