# Generated by Django 4.2 on 2023-10-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_bloginfo_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloginfo',
            table='bloginfo',
        ),
    ]
