# Generated by Django 4.2 on 2023-10-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_bloginfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
