# Generated by Django 4.2 on 2023-10-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_bloginfo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='related_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
